### ISSUE TITLE
GET STARTED DOWS NOT WORK

### ISSUE THREAD

**Issue by Geraldf** [leonardomso/starboy-boilerplate#1]
HI Leonardo, 
great boilerplate, but the get start das not work for me. 
after doing:

> 

1. Clone this repo using https://github.com/leonardomso/react-bolt.git
2. Move to the appropriate directory: cd react-bolt.
3. Run npm install to install dependencies.
4. Run npm start to see the example app at http://localhost:8080.

**the browser opens with the empty screen.** 

webpack issues some warming:

> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (439 KiB).
This can impact web performance.
Assets: 
  vendors~main.js (1.5 MiB)

> WARNING
 in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

and in the browser console I get the error:

> TypeError: undefined is not an object (evaluating 'b.apply')

**Comment by leonardomso** [comment]
I think that this error has something to do with Redux DevTools. Do you have it installed on your browser? Because on the store I put the following code

```
const reduxDevTools =
    window.__REDUX_DEVTOOLS_EXTENSION__ &&
    window.__REDUX_DEVTOOLS_EXTENSION__();

const store = createStore(
    rootReducer,
    compose(
        middleware,
        reduxDevTools
    )
);
```

With this code, it's possible to see and manipulate directly from the browser.

**Comment by denisinla** [comment]
@Geraldf replace the ``store/index.js`` with the following to get up and running on Safari/Firefox:

```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import logger from 'redux-logger';

import rootReducer from '../reducers';

const middleware = applyMiddleware(thunk, logger);

const reduxDevTools = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const store = createStore(
    rootReducer,
    reduxDevTools(
        middleware
    )
);

export default store;

```

Also @leonardomso changing your store's reduxDevTools variable to use ``window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ``should alleviate the issue with those not using Chrome.

**Comment by ultamatt** [comment]
Also ran into this issue. Also the code above solved for me. Thanks!
